### ISSUE TITLE
Unable to create record

### ISSUE THREAD

**Issue by Gautam-Shivani** [tyoshikawa1106/lightning-force-create-record#1]
When using the sample code, an error is coming - "Something has gone wrong. Cannot read property 'setParams' of undefined.
Please try again."

Could you please help me out in this. 
Thank you.

**Comment by tyoshikawa1106** [comment]
Hi, Gautam-Shivani. Thanks for message.
I checked sample code. Error did not occur.

I made a package.　It is the code that was used to verify.
Please try at this.

**sample code package**
[https://login.salesforce.com/packaging/installPackage.apexp?p0=04tG0000000AbJA](https://login.salesforce.com/packaging/installPackage.apexp?p0=04tG0000000AbJA)

Thank you.

**Comment by akshaysGit** [comment]
Hi  Tyoshi,

I tried your code but it gives me error similar to one reported above.

Can you please suggest what needs to be done?
I have uploaded an error image. 

Thanks,
 Dattaraj 
![image](https://cloud.githubusercontent.com/assets/20942531/21338795/6d7f732e-c69f-11e6-8c33-3a7cf24aeaa4.png)

**Comment by tyoshikawa1106** [comment]
Oh! Thanks for Message.
Hmm.. I will check it when I have time.

**Comment by akshaysGit** [comment]
Thanks for responding so quickly. I really appreciate that. 
Please check it as soon as you get time as I need this one very badly.
Appreciate your help in advance.

**Comment by tyoshikawa1106** [comment]
okay!! I understood the cause!
createRecordEvent is Salesforce1 Application Only!

You need to prepare a page for Salesforce 1 in App Builder.
Please change implements.

<img width="400" alt="createrecordevent" src="https://cloud.githubusercontent.com/assets/2088447/21339127/03723b58-c6c0-11e6-8165-1a3e2e192075.png">

Thanks!!

**Comment by akshaysGit** [comment]
Thanks a ton for replying so quickly and taking time from your schedule. You really saved my day.

This is working now. It looks like when we preview it in app (from Dev console) its not working however when it was created as a lightning page then it is working.

I really appreciate your help.

Thanks,
Dattaraj

**Comment by tyoshikawa1106** [comment]
Great! I'm glad I found it useful.
